# Generated by Django 5.0 on 2026-02-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='e.g., SCI, ART, ENG', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('dean_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Officer's clearance department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='clearance_app.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text="Student's academic faculty", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='clearance_app.faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty_assignment',
            field=models.ForeignKey(blank=True, help_text='For Faculty dept officers: which faculty they handle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_officers', to='clearance_app.faculty'),
        ),
    ]
